### ISSUE TITLE
Problem to installation

### ISSUE THREAD

**Issue by matheusdelima** [rongeb/anit_cms_for_zf3#1]
`Additional information:
Zend\View\Exception\RuntimeException
File:
/Applications/XAMPP/xamppfiles/htdocs/zf3/anit_cms/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php:497
Message:
Zend\View\Renderer\PhpRenderer::render: Unable to render template "Sitepublic/Sitepublic/"; resolver could not resolve to a file`

**Comment by rongeb** [comment]
Hello,

Thanks for your issue, I am going to take a look if there's a problem. 

For information, you have 2 phtml files as an example for a public web site : index and blog.
These 2 pages and their contents have been recorded in the app to show the way it works.

Maybe you don't have a phtml file in the module Sitepublic in "view/sitepublic/sitepublic"
In order to create a page :
1) you have to declare a page as a public page (Page tab of the backoffice)
2) you create the phtml file manually in the path "Sitepublic/view/sitepublic/sitepublic"
3) you add your html contents related to the page

And it should work. If I find something wrong in the code, I will let you know and push a fix.

Regards.

**Comment by rongeb** [comment]
Hello,

I downloaded the project from github
I put the project on an apache server 
I called /sitepublic with a browser
I had an error because it was necessary to  create the cache folder (I updated the project, it exists by default right now)
After creating the folder I called again the page and it works.

In order to help you,  please give me more details.

regards.
